data:
    dataset: "FashionMNIST"
    image_size: 28
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 8      # 4  16

# 可运行
#model:
#    type: "simple"
#    in_channels: 1
#    out_ch: 1
#    ch: 96
#    ch_mult: [1, 2, 2]
#    num_res_blocks: 2
#    attn_resolutions: [ ]    # [2,] ?
#    dropout: 0.1
#    var_type: fixedlarge
#    ema_rate: 0.9999
#    ema: False  # True
#    resamp_with_conv: True

model:
    type: "simple"
    in_channels: 1
    out_ch: 1
    ch: 128
    ch_mult: [1, 2, 2 ]     # 问题在这 [1, 2, 2, 2 ]
    num_res_blocks: 2
    attn_resolutions: [16 ]    # [2,] ?
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: False  # True
    resamp_with_conv: True

#model:
#    type: "simple"
#    in_channels: 1
#    out_ch: 1
#    ch: 128
#    ch_mult: [1, 2, 2, 2]
#    num_res_blocks: 2
#    attn_resolutions: [16, ]    # [2,] ?
#    dropout: 0.1
#    var_type: fixedlarge
#    ema_rate: 0.9999
#    ema: False  # True
#    resamp_with_conv: True


diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 64
    last_only: True
    # ckpt_id: 5000  # 加载的模型索引

training:
    batch_size: 64 # 128
    n_epochs: 1      # 本地训练epoch
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 2000

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0002 # 0.0002 # 200epoch后调整了 lr
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0

fed:
    n_clients: 10
    dirichlet: False
    alpha: 0.1
    num_class: 2      # 当 dirichlet 为 False 时有效，
    round: 400
    save_interval: 50